Add retrying ssh

diff --git a/bash/.bash_profile.d/darwin b/bash/.bash_profile.d/darwin
--- a/bash/.bash_profile.d/darwin
+++ b/bash/.bash_profile.d/darwin
@@ -45,6 +45,31 @@ buwr() {
 
 }
 
+retryssh() {
+    attempts=1
+    while true; do
+        echo "Trying ssh $1 (total attempts: $attempts)"
+        ssh "$1"
+        ssh_exit_code=$?
+        echo "ssh exit code: $ssh_exit_code"
+        if [[ $ssh_exit_code -ne 0 ]]; then
+            echo "Failed. Trying mullvad reconnect"
+            mullvad reconnect
+            while true; do
+                status=$(mullvad status --json | jq -r .state)
+                echo "Mullvad status: $status"
+                if [[ "x$status" -eq "xconnected" ]]; then
+                    echo "Mullvad connected"
+                    break
+                fi
+            done
+        fi
+        ((++attempts))
+        echo "Sleeping 1 second"
+        sleep 1
+    done
+}
+
 install_tmux_256_color_terminfo
 
 [[ -L $HOME/iCloud ]] || ln -s $HOME/Library/Mobile\ Documents/com~apple~CloudDocs $HOME/iCloud
